### ISSUE TITLE
Automatically update jekyll collections

### ISSUE THREAD

**Issue by enridaga** [reeco-framework/reeco-jekyll#24]
At the moment, collections are referenced from the `_config.yml` files:

```yaml
collections:
    polifonia-project:
        output: true
    smashub:
        output: true
```

However, names of organisations should be automatically derived from `repositories.txt`. Is there a way to add configurations outside the `_config.yml`?
